networks:
  inception:

volumes:
  mariadb_volume:
    name: mariadb_volume
    driver_opts:
      o: bind
      type: none
      device: ${VOLUMES_PATH}/mariadb

  wordpress_volume:
    name: wordpress_volume
    driver_opts:
      o: bind
      type: none
      device: ${VOLUMES_PATH}/wordpress

  static_volume:
    name: static_volume
    driver_opts:
      o: bind
      type: none
      device: ${VOLUMES_PATH}/static

services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      args:
        - WORDPRESS_DATABASE=${WORDPRESS_DATABASE}
        - WORDPRESS_USER=${WORDPRESS_USER}
        - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
    environment:
      - WORDPRESS_DATABASE
      - WORDPRESS_USER
      - WORDPRESS_PASSWORD
    restart: on-failure
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    expose:
      - 3306

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      args:
        - WORDPRESS_DATABASE=${WORDPRESS_DATABASE}
        - WORDPRESS_USER=${WORDPRESS_USER}
        - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
    restart: on-failure
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    expose:
      - 9000

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    restart: on-failure
    ports:
      - 443:443
    depends_on:
      - wordpress
      - redis
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress_volume:/var/www/html

  redis:
    container_name: redis
    build: ./requirements/redis
    depends_on:
      - wordpress
    ports:
      - '6379:6379'
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception

  vsftpd:
    container_name: vsftpd
    build:
      context: requirements/vsftpd
      args:
        - FTP_USER
        - FTP_PASSWORD
    networks:
      - inception
    volumes:
      - wordpress_volume:/home/$FTP_USER/ftp
    ports:
      - "20:20"
      - "21:21"
      - "21000-21010:21000-21010"
    restart: on-failure
    depends_on:
      - nginx

  cadvisor:
    container_name: cadvisor
    build:
      context: requirements/cadvisor
    networks:
      - inception
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always

  adminer:
    container_name: adminer
    build:
      context: requirements/adminer
    networks:
      - inception
    volumes:
      - wordpress_volume:/var/www/html
    restart: always
    depends_on:
      - wordpress

  static:
    build:
      context: .
      dockerfile: requirements/static-website/Dockerfile
    container_name: website
    ports:
      - "80:80"
    restart: always
  # static:
  #   container_name: static
  #   image: static:42
  #   init: true
  #   build:
  #     context: ./requirements/static-website
  #     dockerfile: Dockerfile
  #   networks:
  #     - inception
  #   volumes:
  #     - static_volume:/var/www/html
  #   restart: always
